experiment:
  target_col: is_canceled
  test_size: 0.20
  seed: 42
  cv_folds: 5

decision:
  action_rates: [0.05, 0.10, 0.15, 0.20, 0.30]

cost_matrix:
  tp_value: 180.0
  fp_value: -20.0
  fn_value: -200.0
  tn_value: 0.0
